update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,7 +18,7 @@ jobs:
       - name: Format
         run: make format
       - name: Train
-        run: make train
+        run: make train || (echo "Training failed" && exit 1)
       # - name: Evaluation
       #   env:
       #     REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
